---

- name: Install webserver
  become: true
  become_method: sudo

  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - docker-container